sed -i '1i import { supabase } from '"'"'../lib/supabase'"'"';' src/components/PeopleDiscovery.tsx
sed -i '1i import { useEffect, useState } from '"'"'react'"'"';' src/components/PeopleDiscovery.tsx

# Convert static sample profiles to state and fetch data
sed -i 's/const \[isExpanded, setIsExpanded\] = useState(false);/const \[isExpanded, setIsExpanded\] = useState(false);\n  const \[focusedId, setFocusedId\] = useState<string | null>(null);\n  const \[realProfiles, setRealProfiles\] = useState<Profile\[\]>([]);\n  const \[loading, setLoading\] = useState(true);\n\n  useEffect(() => {\n    const fetchProfiles = async () => {\n      try {\n        const { data, error } = await supabase\n          .from('"'"'profiles'"'"')\n          .select('"'"'*'"'"')\n          .not('"'"'username'"'"', '"'"'is'"'"', null)\n          .limit(5);\n\n        if (error \&\& error.code !== '"'"'42P01'"'"') throw error;\n\n        if (data \&\& data.length > 0) {\n          const mapped: Profile[] = data.map((p: any) => ({\n            id: p.id,\n            name: p.full_name || p.username,\n            role: p.role || '"'"'Member'"'"',\n            description: p.bio || '"'"'No bio provided.'"'"',\n            avatarUrl: p.avatar_url || '"'"'https:\/\/api.dicebear.com\/7.x\/avataaars\/svg?seed='"'"' + p.username,\n            location: p.location || '"'"'Unknown Location'"'"'\n          }));\n          setRealProfiles(mapped);\n        } else {\n          setRealProfiles(SAMPLE_PROFILES);\n        }\n      } catch (err) {\n        console.warn('"'"'Could not fetch real profiles'"'"', err);\n        setRealProfiles(SAMPLE_PROFILES);\n      } finally {\n        setLoading(false);\n      }\n    };\n    fetchProfiles();\n  }, []);/g' src/components/PeopleDiscovery.tsx

# Prevent second focusedId useState declaration
sed -i 's/  const \[focusedId, setFocusedId\] = useState<string | null>(null);//g' src/components/PeopleDiscovery.tsx
sed -i 's/profiles={SAMPLE_PROFILES}/profiles={realProfiles.length > 0 ? realProfiles : SAMPLE_PROFILES}/g' src/components/PeopleDiscovery.tsx

# Update final CTA
sed -i 's/<p className="text-xl font-medium text-cyan-400\/80">\n              Start finding the people you need\n            <\/p>/<p className="text-xl font-medium text-cyan-400\/80">\n              Explore the full community network\n            <\/p>/g' src/components/PeopleDiscovery.tsx

sed -i 's/<button className="bg-gradient-to-r from-cyan-500 to-purple-600 hover:from-cyan-400 hover:to-purple-500 text-white font-bold py-3 px-8 rounded-xl shadow-\[0_0_20px_rgba(34,211,255,0.2)\] hover:shadow-\[0_0_30px_rgba(34,211,255,0.4)\] transition-all hover:scale-105 group flex items-center gap-2">/<a href="\/explore" className="bg-gradient-to-r from-cyan-500 to-purple-600 hover:from-cyan-400 hover:to-purple-500 text-white font-bold py-3 px-8 rounded-xl shadow-\[0_0_20px_rgba(34,211,255,0.2)\] hover:shadow-\[0_0_30px_rgba(34,211,255,0.4)\] transition-all hover:scale-105 group flex items-center gap-2">/g' src/components/PeopleDiscovery.tsx
sed -i 's/Create your profile\n            <\/button>/Explore All Builders\n            <\/a>/g' src/components/PeopleDiscovery.tsx
